/*
 * Since C++20, there is an option to add initialize statement to range-based for loop
 */

#include <iostream>
#include <ranges> // Let's to use iota_view:
				  // a view consisting of a sequence generated by repeatedly incrementing
				  // an initial value

int main()
{
	//// We can declare this variable here or directly in range-based for loop
	//constexpr double multiplier{ 4 };

	for (constexpr double multiplier{ 4 }; const auto i : std::ranges::iota_view{ 1, 11 })
		std::cout << "result: " << (i * multiplier) << std::endl;

	return 0;
}